name: CI/CD Process
on:
  workflow_call:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
    - name: Validate Nix files
      run: |
        nix-instantiate --parse ./hp-15s-eq2004nl-configuration/*.nix
        nix-instantiate --parse ./shells/*.nix

  test-release:
    needs:
      - check
    runs-on: ubuntu-latest
    concurrency:
      group: test-release
      cancel-in-progress: false
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - uses: cachix/install-nix-action@v27
      - uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm install
          npx semantic-release --dry-run --branches ${{ steps.extract_branch.outputs.branch }}

  release:
    needs:
      - check
      - test-release
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    concurrency:
      group: release
      cancel-in-progress: false
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - uses: cachix/install-nix-action@v27
      - uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm install
          npx semantic-release

  success:
    runs-on: ubuntu-latest
    needs:
      - check
      - test-release
      - release
    if: >-
      always() && (
        contains(join(needs.*.result, ','), 'failure')
        || !contains(join(needs.*.result, ','), 'cancelled')
      )
    steps:
      - name: Verify that there were no failures
        run: ${{ !contains(join(needs.*.result, ','), 'failure') }}
